#!/bin/bash

# -Wc,-std=c++0x

# Default make  target

TARGET=""
VERBOSE=""
MESSAGE=""
SIGNING_PASSWORD=""
TOOLCHAIN_FILE="`pwd`/toolchain/qnx.toolchain.cmake"
if [ -f CMakeCache.txt ]; then
    if grep --quiet "$TOOLCHAIN_FILE" CMakeCache.txt; then
	# same toolchain
	echo "** Continue using $TOOLCHAIN_FILE"
    else
	# diffrent toolchain - reload
	echo "** Toolchain not found - force to reconfigure build."
	PLAT=`grep PLAT_SDK CMakeCache.txt | cut -f 2 -d=`
	rm -rf cmake.ts CMakeCache.txt CMakeFiles
    fi
fi

# Check and rebuild arguments
options=()  # the buffer array for the parameters
while [[ $1 ]]
do
    case "$1" in
	rebuild*)
	    rm -f cmake.ts CMakeCache.txt CMakeFiles
	    ;;
	playbook*)
	    PLAT="/Developer/SDKs/bbndk-2.1.0/bbndk-env.sh"
	    if [ -f CMakeCache.txt ]; then
		if grep --quiet "$PLAT" CMakeCache.txt; then
		    echo "** Config unchanged."
		else
		    echo "** Force to reconfigure build."
		    rm -rf cmake.ts CMakeCache.txt CMakeFiles
		fi
	    fi
	    ;;
	bb10*)
	    PLAT="/Developer/SDKs/bbndk/bbndk-env.sh"
	    if [ -f CMakeCache.txt ]; then
		if grep --quiet "$PLAT" CMakeCache.txt; then
		    echo "** Config unchanged."
		else
		    echo "** Force to reconfigure build."
		    rm -rf cmake.ts CMakeCache.txt CMakeFiles
		fi
	    fi
	    ;;
	run*)
	    TARGET="run"
	    MESSAGE=" for target: Run"
	    ;;
	clean*)
	    TARGET="clean"
	    ;;
	password*)
	    SIGNING_PASSWORD="$2"
	    echo "$SIGNING_PASSWORD" > .storepass
	    shift
	    ;;
	verbose*)
	    VERBOSE="VERBOSE=1"
	    ;;
	dist*)
	    TARGET="release"
	    ;;
	debug*)
	    BUILDTYPE="Debug"
	    if [ -f CMakeCache.txt ]; then
		if grep --quiet "CMAKE_BUILD_TYPE:STRING=${BUILDTYPE}" CMakeCache.txt; then
		    echo "** Config unchanged."
		else
		    echo "** Force to reconfigure build."
		    rm -f cmake.ts
		fi
	    fi
	    ;;
	configure*)
	    echo "** Force to reconfigure build."
	    rm -f cmake.ts
	    ;;
	*)
	    options+=("$1")
	    ;;
    esac
    shift
done

# Reload arguments with remaing ones:
set -- "${options[@]}"

if [ ".$PLAT" == "." ]; then
    if [ -f CMakeCache.txt ]; then
	PLAT=`grep PLAT_SDK CMakeCache.txt | cut -f 2 -d=`
    fi
fi
if [ -x "$PLAT" ]; then
    . $PLAT
elif [ ".$PLAT" == "." ]; then
    echo "*** $0: Specify playbook or bb10 for SDK selection."
    exit
else
    echo "*** '$PLAT' not found!'"
    exit
fi

echo "** Platform SDK: $PLAT"

CPU="$1$2"

if [ ".$CPU" == "." ]; then
    set -- "arm" "v7le"
    CPU="$1$2"
    echo "** Target architecture could not be determined. Using: $1/$2"
fi

if [ "$2" == "v7le" ]; then
    CPUDIR="$1le-v7"
    BUSUFFIX="$1v7"
elif [ "$2" == "a9" ]; then
    CPUDIR="$1le-v7"
    CPU="$1v7le"
    BUSUFFIX="$1v7"
    CPUGEN="a9"
else
    CPUDIR="$CPU"
    BUSUFFIX="$1"
fi

if [ "$STAGE_DIR" == "" ]; then
    STAGE_DIR="${QNX_TARGET}"
    echo "** Staging directory could not be determined. Using: $STAGE_DIR"
else
    echo "** Using staging directory: $STAGE_DIR"
fi

if [ ! -z "$USE_ICECC" ] ; then
    CC_COMMAND=icecc
    echo "Using icecream for distributed compiling"
else
    CC_COMMAND=$QNX_HOST/usr/bin/qcc
fi

if [ -z "$SIGNING_PASSWORD" ] ; then
    if [ -f CMakeCache.txt ]; then
	SIGNING_PASSWORD=`grep SIGNING_PASSWORD CMakeCache.txt | cut -f 2 -d=`
    fi
    if [ -z "$SIGNING_PASSWORD" ] ; then
	if [ -f .storepass ]; then
	    SIGNING_PASSWORD=`cat .storepass`
	fi
    fi
    if [ -z "$SIGNING_PASSWORD" ] ; then
	if [ ".$TARGET" == ".run" ] ; then
	    echo "** Signing password is required for building a package."
	    exit 1
	fi
    fi
fi

if [ -z "$BUILDTYPE" ] ; then
    if [ -f CMakeCache.txt ]; then
	BUILDTYPE=`grep CMAKE_BUILD_TYPE CMakeCache.txt | cut -f 2 -d=`
    fi
    if [ -z "$BUILDTYPE" ] ; then
	BUILDTYPE="Release"
    fi
fi

echo "** Build type: $BUILDTYPE"

if [ ! -z "$PROFILE" ] ; then
    PROFILER_FLAGS="-p"
else
    PROFILER_FLAGS=""
fi

if [ "$CCWRAP" ] ; then
    CMAKE_EXTRA_OPTIONS=" \
        -DCMAKE_C_COMPILER_ARG1=qcc \
        -DCMAKE_CXX_COMPILER_ARG1=qcc"
    CC_COMMAND="$CCWRAP"
fi

if [ "$CPUGEN" == "a9" ] ; then
    CMAKE_EXTRA_OPTIONS=" \
        -DTARGET_IS_WINCHESTER=1 \
        $CMAKE_EXTRA_OPTIONS"
fi

if [ `uname` == "Darwin" ] ; then
    CMAKE_EXTRA_OPTIONS=" \
        -DCMAKE_SKIP_RPATH='ON' \
        $CMAKE_EXTRA_OPTIONS"
fi

sdl_root="$HOME/Software/SDL-1/dist/"
if [ ! -d $sdl_root ]; then
    echo "** SDL installation not found at $sdl_root"
    exit
fi

script=`basename $0`

# check for terminal-notifier command
command -v terminal-notifier >/dev/null && { terminalnotifier="terminal-notifier"; } || { echo "*** terminal-notifier command not found."; terminalnotifier="command -v "; }

START=$(date +%s)
if [ ! -f cmake.ts -o  ! -f CMakeCache.txt -o CMakeLists.txt -nt cmake.ts -o $script -nt cmake.ts ]; then
 rm -rf cmake.ts
 cmake \
    -DPLAT_SDK="$PLAT" \
    -DCPU="$CPU" \
    -DBUSUFFIX="$BUSUFFIX" \
    -DCC_COMMAND="$CC_COMMAND" \
    -DQNX_TARGET="$QNX_TARGET" \
    -DQNX_HOST="$QNX_HOST" \
    -DSTAGE_DIR="$STAGE_DIR" \
    -DQCC_VERSION_CHECK="`pwd`/toolchain/check_qcc_version" \
    -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE" \
    -DCMAKE_SYSTEM_PROCESSOR="$CPUDIR" \
    -DCMAKE_EXTRA_OPTIONS="$CMAKE_EXTRA_OPTIONS" \
    -DCMAKE_BUILD_TYPE="$BUILDTYPE" \
    -DCMAKE_INSTALL_PREFIX="$STAGE_DIR" \
    -DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=TRUE \
    -DSDLDIR="$sdl_root" \
    -DSIGNING_PASSWORD="$SIGNING_PASSWORD" \
    -DDEBUG_TOKEN="`pwd`/debugtoken1.bar" \
    -DDEVICE_PASSWORD="1234" \
    -G"Eclipse CDT4 - Unix Makefiles" \
    $CMAKE_EXTRA_OPTIONS \
    $3 ./ \
&& touch cmake.ts \
&& make $VERBOSE $TARGET \
&& (END=$(date +%s); DIFF=$(echo "$END - $START" | bc); $terminalnotifier -message "$script script finished$MESSAGE Execution time: $DIFF sec." -title BUILDER >> /dev/null)
else
    END=$(date +%s)
    DIFF=$(echo "$END - $START" | bc)
    make $VERBOSE $TARGET && $terminalnotifier -message "$script script finished$MESSAGE Execution time: $DIFF sec." -title BUILDER >> /dev/null
fi
