
#if defined(__arm__) || defined(arm) || defined(__ARM__) || defined(__ARM_NEON__)

// skip - arm build is fine

#else

// dummy definitions for incomplete x86 build for Windows Phone 8;
// since we build for mobile only, exclude only __arm__ builds.

void s3eTimerGetMs() {}
void s3eDebugIsDebuggerPresent() {}
void s3eDebugOutputString() {}
void s3ePointerGetInt() {}
void s3ePointerRegister() {}
void s3ePointerUnRegister() {}
void s3eConfigGetString() {}
void s3eDeviceYield() {}
void s3eDeviceRegister() {}
void s3eDeviceUnRegister() {}
void s3eDeviceCheckQuitRequest() {}
void s3eKeyboardUpdate() {}
void s3ePointerUpdate() {}
void s3eDebugAssertShow() {}
void s3eExtGetHash() {}
void s3eDeviceLoaderCallStart() {}
void s3eDeviceLoaderCallDone() {}
void s3eAccelerometerStart() {}
void s3eAccelerometerStop() {}
void s3eAccelerometerGetX() {}
void s3eAccelerometerGetY() {}
void s3eAccelerometerGetZ() {}
void s3eFileOpen() {}
void s3eFileClose() {}
void s3eFileRead() {}
void s3eFileGetSize() {}
void s3eMallocBase() {}
void s3eFreeBase() {}
void s3eSoundSetInt() {}
void s3eSoundGetErrorString() {}
void s3eSoundGetFreeChannel() {}
void s3eSoundChannelPlay() {}
void s3eAudioSetInt() {}
void s3eAudioPlay() {}
void s3eAudioStop() {}
void s3eAudioIsPlaying() {}
void s3eAudioIsCodecSupported() {}
void s3eFileSeek() {}
void s3eFileTell() {}
void s3eGLGetInt() {}
void s3eFileCheckExists() {}
void s3eConfigGetInt() {}
void s3eKeyboardGetState() {}
void s3eFileWrite() {}
void s3eSurfaceGetInt() {}
void s3eDeviceGetInt() {}
void s3eMemoryGetInt() {}
void s3eMemorySetInt() {}
void s3eMemoryHeapCreate() {}
void s3eFileGetFileInt() {}
void s3eSurfaceRegister() {}
void s3eSurfaceUnRegister() {}
void s3eSurfacePtr() {}
void s3eSurfaceInfo() {}
void s3eSurfaceSetup() {}
void s3eFileOpenFromMemory() {}
void s3ePointerGetX() {}
void s3ePointerGetY() {}
void s3eSurfaceShow() {}
void s3eFileGetChar() {}
void s3eReallocBase() {}
void s3eGLRegister() {}
void s3eGLUnRegister() {}
void s3eGLGetNativeWindow() {}
void s3eFileGetFileString() {}
void s3eFileMakeDirectory() {}
void s3eFileDelete() {}
void s3eFileAddUserFileSys() {}
void s3eCompressionDecompInit() {}
void s3eFile() {}
void s3eCompressionDecompRead() {}
void s3eCompressionDecompFinal() {}
void s3eFileFlush() {}
void s3eFileEOF() {}
void s3eDebugErrorShow() {}
void s3eTimerGetUTC() {}
void s3eDeviceGetString() {}
void s3eDeviceYieldUntilEvent() {}
void s3eDeviceExit() {}
void s3eFileGetError() {}
void s3eFileDeleteDirectory() {}
void s3eFileRename() {}
void s3eFileTruncate() {}
void s3eTimerGetLocaltimeOffset() {}
void s3eDebugSetInt() {}
void s3eDebugRegister() {}
void s3eDebugTraceLine() {}
void s3eDebugTraceChannelSwitch() {}
void s3eMemoryHeapAddress() {}
void s3eTimerGetUST() {}
void s3eSocketGetString() {}
void s3eMemorySetUserMemMgr() {}
void s3eMemoryUsrMgr() {}
void s3eSocketGetError() {}
void s3eInetAddress() {}
void s3eInetNtohl() {}
void s3eInetHtonl() {}
void s3eInetNtohs() {}
void s3eInetHtons() {}
void s3eSocketCreate() {}
void s3eSocketClose() {}
void s3eSocketBind() {}
void s3eSocketGetLocalName() {}
void s3eSocketGetPeerName() {}
void s3eSocketConnect() {}
void s3eSocketSend() {}
void s3eSocketRecv() {}
void s3eSocketRecvFrom() {}
void s3eSocketSendTo() {}
void s3eSocketListen() {}
void s3eSocketAccept() {}
void s3eSocketReadable() {}
void s3eSocketWritable() {}
void s3eDebugGetInt() {}
void s3eDebugPrint() {}
void s3eKeyboardSetInt() {}
void s3eKeyboardRegister() {}
void s3eTimerSetTimer() {}
void s3eDeviceSetInt() {}
void s3eInetAton() {}
void s3eInetNtoa() {}
void s3eInetLookup() {}
void s3eFileListDirectory() {}
void s3eFileListNext() {}
void s3eFileListClose() {}
void s3eCompressionDecomp() {}

// --

void glGetString() {}
void glGetIntegerv() {}
void glGetError() {}
void glClearColor() {}
void glClear() {}
void glColorMask() {}
void glTexParameterf() {}
void glTexParameterfv() {}
void glActiveTexture() {}
void glBindTexture() {}
void glCompressedTexImage2D() {}
void glCompressedTexSubImage2D() {}
void glCopyTexImage2D() {}
void glCopyTexSubImage2D() {}
void glDeleteTextures() {}
void glGenTextures() {}
void glIsTexture() {}
void glTexImage2D() {}
void glTexParameteri() {}
void glTexParameterx() {}
void glTexParameteriv() {}
void glTexParameterxv() {}
void glTexSubImage2D() {}
void glGenerateMipmap() {}
void glAlphaFunc() {}
void glClearDepthf() {}
void glClipPlanef() {}
void glColor4f() {}
void glDepthRangef() {}
void glFogf() {}
void glFogfv() {}
void glFrustumf() {}
void glGetClipPlanef() {}
void glGetLightfv() {}
void glGetMaterialfv() {}
void glGetTexEnvfv() {}
void glGetTexParameterfv() {}
void glLightModelf() {}
void glLightModelfv() {}
void glLightf() {}
void glLightfv() {}
void glLineWidth() {}
void glMaterialf() {}
void glMaterialfv() {}
void glMultMatrixf() {}
void glMultiTexCoord4f() {}
void glNormal3f() {}
void glOrthof() {}
void glPointParameterf() {}
void glPointParameterfv() {}
void glPointSize() {}
void glPolygonOffset() {}
void glRotatef() {}
void glScalef() {}
void glTexEnvf() {}
void glTexEnvfv() {}
void glTranslatef() {}
void glAlphaFuncx() {}
void glBlendFunc() {}
void glClearColorx() {}
void glClearDepthx() {}
void glClearStencil() {}
void glClientActiveTexture() {}
void glClipPlanex() {}
void glColor4x() {}
void glColorPointer() {}
void glCullFace() {}
void glDepthFunc() {}
void glDepthMask() {}
void glDepthRangex() {}
void glDisable() {}
void glDisableClientState() {}
void glDrawArrays() {}
void glDrawElements() {}
void glEnable() {}
void glEnableClientState() {}
void glFinish() {}
void glFlush() {}
void glFogx() {}
void glFogxv() {}
void glFrontFace() {}
void glFrustumx() {}
void glGetClipPlanex() {}
void glGetLightxv() {}
void glGetMaterialxv() {}
void glGetPointerv() {}
void glGetTexEnviv() {}
void glGetTexEnvxv() {}
void glGetTexParameteriv() {}
void glGetTexParameterxv() {}
void glHint() {}
void glIsEnabled() {}
void glLightModelx() {}
void glLightModelxv() {}
void glLightx() {}
void glLightxv() {}
void glLineWidthx() {}
void glLogicOp() {}
void glMaterialx() {}
void glMaterialxv() {}
void glMultMatrixx() {}
void glMultiTexCoord4x() {}
void glNormal3x() {}
void glNormalPointer() {}
void glOrthox() {}
void glPixelStorei() {}
void glPointParameterx() {}
void glPointParameterxv() {}
void glPointSizex() {}
void glPolygonOffsetx() {}
void glPopMatrix() {}
void glPushMatrix() {}
void glReadPixels() {}
void glRotatex() {}
void glSampleCoveragex() {}
void glScalex() {}
void glShadeModel() {}
void glStencilFunc() {}
void glStencilMask() {}
void glStencilOp() {}
void glTexCoordPointer() {}
void glTexEnvi() {}
void glTexEnvx() {}
void glTexEnviv() {}
void glTexEnvxv() {}
void glTranslatex() {}
void glVertexPointer() {}
void glPointSizePointerOES() {}
void glBlendColor() {}
void glBlendEquation() {}
void glBlendEquationSeparate() {}
void glBlendFuncSeparate() {}
void glDisableVertexAttribArray() {}
void glEnableVertexAttribArray() {}
void glGetRenderbufferParameteriv() {}
void glGetVertexAttribfv() {}
void glGetVertexAttribiv() {}
void glGetVertexAttribPointerv() {}
void glReleaseShaderCompiler() {}
void glStencilFuncSeparate() {}
void glStencilMaskSeparate() {}
void glStencilOpSeparate() {}
void glVertexAttrib1f() {}
void glVertexAttrib1fv() {}
void glVertexAttrib2f() {}
void glVertexAttrib2fv() {}
void glVertexAttrib3f() {}
void glVertexAttrib3fv() {}
void glVertexAttrib4f() {}
void glVertexAttrib4fv() {}
void glVertexAttribPointer() {}
void glGetFloatv() {}
void glLoadMatrixf() {}
void glLoadIdentity() {}
void glLoadMatrixx() {}
void glMatrixMode() {}
void glScissor() {}
void glViewport() {}
void glGetBooleanv() {}
void glGetFixedv() {}
void glBindBuffer() {}
void glBufferData() {}
void glBufferSubData() {}
void glDeleteBuffers() {}
void glGetBufferParameteriv() {}
void glGenBuffers() {}
void glIsBuffer() {}
void glAttachShader() {}
void glBindAttribLocation() {}
void glCompileShader() {}
void glCreateProgram() {}
void glCreateShader() {}
void glDeleteProgram() {}
void glDeleteShader() {}
void glDetachShader() {}
void glGetActiveAttrib() {}
void glGetActiveUniform() {}
void glGetAttachedShaders() {}
void glGetAttribLocation() {}
void glGetProgramiv() {}
void glGetProgramInfoLog() {}
void glGetShaderiv() {}
void glGetShaderInfoLog() {}
void glGetShaderPrecisionFormat() {}
void glGetShaderSource() {}
void glGetUniformfv() {}
void glGetUniformiv() {}
void glGetUniformLocation() {}
void glIsProgram() {}
void glIsShader() {}
void glLinkProgram() {}
void glShaderBinary() {}
void glShaderSource() {}
void glUniform1f() {}
void glUniform1fv() {}
void glUniform1i() {}
void glUniform1iv() {}
void glUniform2f() {}
void glUniform2fv() {}
void glUniform2i() {}
void glUniform2iv() {}
void glUniform3f() {}
void glUniform3fv() {}
void glUniform3i() {}
void glUniform3iv() {}
void glUniform4f() {}
void glUniform4fv() {}
void glUniform4i() {}
void glUniform4iv() {}
void glUniformMatrix2fv() {}
void glUniformMatrix3fv() {}
void glUniformMatrix4fv() {}
void glUseProgram() {}
void glValidateProgram() {}
void glBindFramebuffer() {}
void glBindRenderbuffer() {}
void glCheckFramebufferStatus() {}
void glDeleteFramebuffers() {}
void glDeleteRenderbuffers() {}
void glFramebufferRenderbuffer() {}
void glFramebufferTexture2D() {}
void glGenFramebuffers() {}
void glGenRenderbuffers() {}
void glGetFramebufferAttachmentParameteriv() {}
void glIsFramebuffer() {}
void glIsRenderbuffer() {}
void glRenderbufferStorage() {}

#endif
